config/routes.rb
Rails.application.routes.draw do
  resources :follows, only: [:create, :destroy]

  #resources :posts, only: [:index, :new, :create, :edit, :update]
  resources :posts do
    resources :comments
  end
  # root "posts#index"

  # resources :users, only: [:new, :create]
  resources :users
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  
 
  resources :sessions, only: [:new, :create, :login, :welcome, :destroy]
  root "sessions#new"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, dependent: :destroy
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: :follow_by, class_name: 'User'
  belongs_to :followee, foreign_key: :follow_to, class_name: 'User'

  # belongs_to :follower, class_name: 'User'
  # belongs_to :followee, class_name: 'User'

  validates :follow_by, presence: true
  validates :follow_to, presence: true

  # validates :follower, presence: true
  # validates :followee, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, length: {minimum: 1, maximum: 200}

  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  #validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

  has_many :posts, dependent: :destroy


  has_many :followed_users, foreign_key: :follow_by, class_name: 'Follow'
  has_many :followees, through: :followed_users
  
  has_many :following_users, foreign_key: :follow_to, class_name: 'Follow'
  has_many :followers, through: :following_users



  def follow(user_id)
    followed_users.create(follow_to: user_id)
  end

  def unfollow(user_id)
    followed_users.find_by(follow_to: user_id).destroy
  end

  def following?(user_id)
    following_users.pluck(:id).include?(user_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  protect_from_forgery with: :null_session

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])  
  end

  def logged_in?
    !current_user.nil?  
  end

  def authorized
   # redirect_to '/welcome' unless logged_in?
   redirect_to login_path unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all.order(created_at: :desc)
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  
  def show
    @comment = Comment.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
     redirect_to new_post_comment_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :commentbox)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    # @user = User.find(params[:follower_id])
    current_user.follow(user)
    redirect_to @user
    # redirect_to :back
  end

  def destroy
    # @user = Follow.find(params[:id]).follower_id
    current_user.unfollow(user)
    redirect_to @user
    # redirect_to :back
  end

  private

  def find_user
    @user User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: %i[ show edit update destroy ]
  before_action :logged_in?

  
  def index
    @posts = Post.all.order(created_at: :desc).with_attached_images
  end

  def show
    @post = Post.find(params[:id])
    # @comment = Comment.find(params[:post_id])
  end


  def new
    @post = Post.new
  end
    
  def create
    # Post.create(post_params)
    @post = Post.new(post_params)
    @post.user_id = current_user.id     # current_user_id is Associated with post id 
    # current_user.posts.create(post_params)
    if @post.save 
      redirect_to posts_path
      # redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, status: :see_other
  end


  private
   
  def post_params
    params.require(:post).permit(:username, :body, images: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]
  # def new
  #   @user = User.new
  # end

  def login
  end

  def create
    @user = User.find_by(username: params[:username])
    # session[:id] = @user.id unless session[:user_id] 
    session[:user_id] = @user.id 
    if @user && @user.authenticate(params[:password])
      redirect_to '/posts'
    else
      redirect_to '/login'
      # flash[:danger] = 'invalid username and password'
      # flash[:alert] = 'invalid username and password'
      # render "new"
    end
  end

  def welcome
  end

  def page_requires_login
  end

  def destroy
    # @user = User.find_by(params[:username])
    # if @user.present?
    session[:user_id] = nil
      # @user.destroy
    # end
    redirect_to '/login'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    UserMailer.welcome_email(@user).deliver
    session[:user_id] = @user.id
    if @user.valid?
      @user.save
      redirect_to '/welcome', notice: 'User was sucessfully created!'
    else  
      redirect_to new_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/welcome'
  end


  def follow
    # binding.pry
    @user = User.find(params[:id])
    # @current_user.follow_by << @user
    @current_user.followers << @user
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    @current_user.followed_users.find_by(follow_by: @user.id).destroy
    # redirect_back(fallback_location: user_path(@user))
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= current_user.username %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.commentbox %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :commentbox %><br>
    <%= form.text_area :commentbox %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/sessions/destroy.html.erb</p>

app/views/comments/index.html.erb
<div class="center2">Comments List</div>
<div class="comments">
  <% @comments.each do |comment| %>
    <div class="comment">
        <strong><u>Comment by</u></strong>
        <span><%= comment.commenter %> -</span>
        <span><%= comment.commentbox %> -</span>
        <em>on- <%= comment.created_at %></em>
        <%= link_to 'Delete', post_comments_path(comment.post, comment), method: :delete, data: { turbo_method: :delete,
                     turbo_confirm: 'Are you sure?'}, class: "mt-2 btn btn-primary" %>
        <%#= link_to "Delete comment", @comment, turbo_method: :delete %>
        <%#= link_to 'Delete', post_comment_path(@comment.post, @comment),method: :delete,
                              data: { confirm: "Are you sure ?"} %>
        <%#= link_to 'delete',{ controller: "comments", action: "destroy", id: user.id }, data: { confirm: 'Are you are?' }, method: :delete %>
    </div>
    <hr />
  <% end %>
</div>
<br>
<div class="corner">
  <%= link_to "Back to posts", posts_path, class: "mt-2 btn btn-primary" %>
</div>

app/views/comments/new.html.erb
<h1>Add a Comment</h1>
<h2>Comments</h2>
<%= render @post.comments %>
<%= link_to "Delete comment", post_comments_path %>
<br>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<br>
<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Virtualworld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style type="text/css">
      .center {
        color: blue;
        text-align: center;
        font-size: 48px;
        font-family: "Times New Roman";
        text-decoration: underline

      }
      .center2 {
        color: black;
        text-align: center;
        font-size: 30px;
        font-family: "Times New Roman";
        text-decoration: underline

      }
       th, td {
        width:150px;
        text-align:center;
        padding:5px
             
      }
      .profile {
        color: blue;    
        text-align: left;
      }
      .left{
        text-align: left;
        position: absolute;
        top: 10px;
        left: 19px;
      }
      body {
        background-color: lightblue;
      } 
      .corner {
        text-align: right;
        position: absolute;
        top: 10px;
        right: 19px;
      }
      .login{
        text-align: center;
      }


    </style>
  </head>

  <body align="center" >
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Title, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %> 
    <%#= form.text_area :content, placeholder: "Enter article content here", size: "50x10" %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, placeholder: "Enter the message", class: "Form-control", rows: 3 %>
  </div>

 <!-- <div>
    <%#= form.label :likes_count, style: "display: block" %>
    <%#= form.number_field :likes_count %>
  </div>

  <div>
    <%#= form.label :reposts_count, style: "display: block" %>
    <%#= form.number_field :reposts_count %>
  </div> -->

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.username %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>Likes count:</strong>
    <%= post.likes_count %>
  </p>

  <p>
    <strong>Total comments:</strong>
    <%= post.comments.size %>
  </p>

<!--   <p>
    <strong>Reposts count:</strong>
    <%#= post.reposts_count %>
  </p> -->

  <p>
    <strong>Pictures:</strong>
    <%= post.images %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="profile">
  <h3>Login Profile:<%= current_user.username %></h3>
</div>
<h1>Editing post</h1>
<%= render "form", post: @post %>
<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="profile">
    <h3>Login Profile:<%= current_user.username %></h3>
    <%# if session[:user_id] %>
    <%# end %>
    Followers<h6 style="color:black;"><%= current_user.followed_users.count %></h6>
    Following<h6 style="color:black;"><%= current_user.following_users.count %></h6>
</div>
<div class="corner">
    <%= link_to 'Logout', logout_path, :method => :delete, class: "btn btn-primary" %>
</div>
<div class="container">
    <div class="center">Posts Listing</div>
    <div>
        <table>
            <tr>
                <th>User </th>
                <th>Title </th>
                <th>Pictures</th>
                <th>Body </th>
                <th>Total Comments</th>
                <th>Likes </th>
            </tr>
            <% @posts.each do |post| %>
            <tr>
                <td><%= post.user.username %></td>
                <td><%= post.username %></td>
                <td><%= image_tag post.images.last, width: "200px", height: "150px" if post.images.present? %></td>
                <td><%= post.body %></td>
                <td><%= post.comments.size %></td>
                <td><%= post.likes_count %></td>
                <td><%= link_to "Write comments", new_post_comment_path(post) %></td>
                <td><%= link_to "Edit", edit_post_path(post) %></td>
                <td><%= link_to "Destroy", post_path(post), turbo_method: :delete %></td>
            </tr>
            <% end %>
        </table>
    </div>
    <%= link_to "New Post", new_post_path, class: "btn btn-primary" %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="profile">
  <h3>Login Profile:<%= current_user.username %></h3>
</div>
<h3>Show user Post</h3>
<%= render @post %>
<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %> |
  <%= link_to "Destroy this post", post_path(@post), turbo_method: :delete %>
</div>
<h3>Comments</h3>
<%= render @post.comments %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/sessions/destroy.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%>
  <%= f.text_field :username%><br>
  <br>
  <%= f.label :password%>
  <%= f.password_field :password%><br>
  <br>
  <%= f.label :email%>
  <%= f.email_field :email%><br>
  <br>
  <%= f.submit "Create Account", class: "btn btn-primary"%>
<%end%>